/* 自動生成——請勿手改。重生：npm run build:sw
 * 內容：service worker 的 precache 清單與版本（版本＝所有檔案內容的雜湊，
 * 改了任何檔就換版本，舊快取自動淘汰）。 */
self.SW_VERSION = "6a55fe0bc8";
self.SW_ASSETS = [
  "app.js",
  "brand/maicoin.png",
  "brand/max.png",
  "chat-context.js",
  "chat-core.js",
  "chat-service.js",
  "chat.html",
  "chat.js",
  "health-core.js",
  "home-core.js",
  "home-service.js",
  "home.html",
  "home.js",
  "host-app.html",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "index.html",
  "insights-core.js",
  "insights-service.js",
  "insights.html",
  "insights.js",
  "investment-analysis.js",
  "kline-core.js",
  "maimate_bot_small_bullish.png",
  "maimate_bot_small.png",
  "maimate_hero.png",
  "manifest.webmanifest",
  "market-core.js",
  "mocks/account.js",
  "mocks/chat.js",
  "mocks/home.js",
  "mocks/onboarding.js",
  "navigation-context.js",
  "onboarding-analysis.js",
  "onboarding-core.js",
  "onboarding.html",
  "onboarding.js",
  "return-core.js",
  "settings.html",
  "settings.js",
  "welcome.html",
  "welcome.js"
];
